name: Check Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Linting
      run: |
        uv run poe ci_check
